# Generated by Django 2.1.3 on 2019-01-24 11:10

from django.db import migrations, models


def initial_data(apps, schema_editor):
    from chat.models import Room
    for name in ('Python', 'Django', 'Channels', 'WebSocket', 'React'):
        Room.objects.create(name=name, max_number=5)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('max_number', models.PositiveIntegerField(default=10, verbose_name='最大聊天人数')),
            ],
        ),
        migrations.RunPython(initial_data),
    ]
